### PR TITLE
json5 to json converter and build step

### PR DESCRIPTION
**Pull request by emortong**
Renovate supports JSON5 but [not for shareable configs](https://github.com/renovatebot/renovate/issues/7674)

This PR adds a build step to the CIrcleCI workflow to transpile JSON5 to JSON.

It also adds the converted JSON to the `.gitignore` to avoid confusion and to avoid having developers modify the `.json` file instead of the `.json5` file, getting the files out of sync.

### CODE REVIEW

**Review by ivomurrell — APPROVED** [review]
The best of both worlds, this is great!

**Comment by apaleslimghost** [comment]
maybe i'm misunderstanding, but i believe for Renovate extending a Github-hosted shareable config, the `.json` file needs to be committed in the repo?

**Comment by emortong** [comment]
@apaleslimghost you are right, hmm how can we avoid developers modifying the .json version if we can't comment on it haha

**Comment by ivomurrell** [comment]
Perhaps we should use a git hook to generate the json and make sure they don't go out of sync?

**Comment by emortong** [comment]
I'll try that, thanks Ivo!

**Comment by emortong** [comment]
using a git-hook could have the same outcome of having the two files and then developers modifying the `.json` instead

but thinking about it now, modifying just the `.json` file would never work since the build step will replace the file, so developers will be forced to look into why their changes were not applied.

I will add a comment on the README and a message to the PR template so that every time someone opens a PR it asks to double-check that all changes were done in the correct file.

**Comment by apaleslimghost** [comment]
the git hook could fail the commit (by returning a non-zero exit code) if the JSON file was edited without editing the JSON5 file?

**Pull request merged**
