### PR TITLE
Prevent Renovate from automatically creating branches and PRs automatically

### PR DESCRIPTION
**Pull request by i-like-robots**
This change disables the automatic creation of branches and PRs by Renovate for all changes. Instead these will be only created when somebody manually approves them. This is to help prevent developers feeling overwhelmed a backlog of largely unimportant PRs and avoid queues in CI.

(This has previously been discussed in dev huddle)

See https://docs.renovatebot.com/configuration-options/#masterissueapproval

### CODE REVIEW

**Comment by simonplend** [comment]
> i'm worried if it's for everything, people will miss a lot of updates

I share this concern. I completely understand developers feeling overwhelmed by a backlog of Renovate pull requests, as I often feel this way too, however they generally provide a useful nudge to keep things up-to-date.

Is there a way that teams could receive a weekly notification of "there are X updated dependencies on project Y"? I'm not optimistic about the Renovate master issues ever being looked at otherwise, and it's seems likely that we'd be back in the position that we were pre-Renovate where the dependencies on many projects were terribly out-of-date.

**Comment by i-like-robots** [comment]
My view on this is that if things are working OK there should be no need to continuously bump dependencies with exceptions for:

1. Fixing urgent security issues
2. Ensuring consistency for our users

With this in mind, the strategy for Renovate/Snyk could look like this:

- Manual approval via the Renovate master issue as the default.
- For dependencies we care about (TBD) override this and enable PRs to be raised automatically...
- ... _but_ only during non-working hours to avoid flooding CI. The master issues can still be used to create quick PRs if necessary.
- Enable Snyk to open PRs for urgent security problems (this appeals to me because I also think this more clearly signals the intent)

Does this sound reasonable and workable @apaleslimghost and @simonplend ?

**Comment by simonplend** [comment]
@i-like-robots That sounds like a great strategy :100: It neatly addresses several of the issues with the current setup, and hopefully it would mean that we actually start using Snyk to patch vulnerable dependencies.

**Comment by apaleslimghost** [comment]
yep, i like this idea, can you update the config to achieve that?

**Comment by i-like-robots** [comment]
I _think_ so. I'll update here with my progress.

**Comment by andygout** [comment]
This was a suggestion that would (as I understand it) allow us to schedule PRs to occur outside of working hours, and is apparently a very quick change. Might be a good stop gap (as people are still complaining about Renovate Bot PRs forming long build queues) until we have a chance to implement the above.

https://financialtimes.slack.com/archives/C03TWD9G1/p1589889939402000?thread_ts=1589880296.391900&cid=C03TWD9G1

> i think you can add a schedule to the renovate config quite quickly https://docs.renovatebot.com/configuration-options/#schedule

> i've set previous projects to "every weekend" but if you wanted them daily you could try "after 10pm and before 5:00am"

**Pull request closed without merging**
